// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTufTtUo_WOa38tZzguaup0--hDOs1C8',
    appId: '1:687623043998:web:faf5cf5523c3ea974bf48f',
    messagingSenderId: '687623043998',
    projectId: 'qunatum-task',
    authDomain: 'qunatum-task.firebaseapp.com',
    storageBucket: 'qunatum-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4oWuQ6Zp-TQmHX-4tgLF7KT_O25iHvVs',
    appId: '1:687623043998:android:9a65c54df5451f294bf48f',
    messagingSenderId: '687623043998',
    projectId: 'qunatum-task',
    storageBucket: 'qunatum-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbokPWD0zU4WcqqPNYMmsZ24YuOiayS2c',
    appId: '1:687623043998:ios:486510e26d3e4a2d4bf48f',
    messagingSenderId: '687623043998',
    projectId: 'qunatum-task',
    storageBucket: 'qunatum-task.appspot.com',
    iosClientId: '687623043998-gjvfj4n0c0ksl3pc1oq1668hfrpaklp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumAssignment',
  );
}
